version: '3.9'
services:
  db:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      MYSQL__PASSWORD: ${MYSQL_PASSWORD:?err}
      MYSQL_DATABASE: ${MYSQL_DB:?err}
      MYSQL_USER: ${MYSQL_USER:?err}
    ports:
      - "3306:3306"
    restart: always