version: '3.9'
services:
  db:
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ADDRESS: 0.0.0.0
    ports:
      - "3307:3307"
    restart: always