version: '3.9'
services:
  db:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      MYSQL__PASSWORD: ${MYSQL_PASSWORD:?err}
      MYSQL_DATABASE: ${MYSQL_DB:?err}
      MYSQL_USER: ${MYSQL_USER:?err}
    ports:
      - "3306:3306"
    restart: always
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "${SERVER_PORT:?err}:${SERVER_PORT:?err}"
    volumes:
      - ./:/usr/local/apps/myapp
      - ignore:/usr/local/apps/myapp/node_modules/

volumes:
  ignore: